<Project>
  <Target Name="PatchWinUIXamlCompiler" AfterTargets="Restore" BeforeTargets="CoreCompile">
    <PropertyGroup>
      <WinUIToolsDir>$(NuGetPackageRoot)microsoft.windowsappsdk.winui\2.3.6\tools\net472</WinUIToolsDir>
      <WinUIRuDir>$(WinUIToolsDir)\ru-RU</WinUIRuDir>
      <WrapperSource>$(MSBuildThisFileDirectory)..\..\Temp\xaml-wrapper\XamlCompilerWrapper.exe</WrapperSource>
    </PropertyGroup>
    <RemoveDir Directories="$(WinUIRuDir)" Condition="Exists('$(WinUIRuDir)')" />
    <Copy SourceFiles="$(WrapperSource)" DestinationFolder="$(WinUIToolsDir)"
          Condition="Exists('$(WrapperSource)') And !Exists('$(WinUIToolsDir)\XamlCompilerWrapper.exe')" />
  </Target>

  <PropertyGroup>
    <XamlCompilerExePath Condition="Exists('$(NuGetPackageRoot)microsoft.windowsappsdk.winui\2.3.6\tools\net472\XamlCompilerWrapper.exe')">$(NuGetPackageRoot)microsoft.windowsappsdk.winui\2.3.6\tools\net472\XamlCompilerWrapper.exe</XamlCompilerExePath>
  </PropertyGroup>
</Project>
